# Generated by Django 4.0.6 on 2022-07-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='link',
        ),
    ]
